# Generated by Django 5.2.5 on 2025-08-19 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, max_length=50, null=True)),
                ('bankLogo', models.ImageField(default='default.png', upload_to='upload_images')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('categoryName', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pdfstatement.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField()),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pdfstatement.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('file', models.FileField(null=True, unique=True, upload_to='')),
                ('amountTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, max_length=20, null=True)),
                ('creditTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, max_length=20, null=True)),
                ('debitTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=19, max_length=20, null=True)),
                ('bankAccount', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pdfstatement.bankaccount')),
                ('pdfParserVersion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdfstatement.bankstatementparser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=500)),
                ('gemini_output', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GeminiUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('transactionDate', models.DateField(blank=True, null=True)),
                ('postingDate', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('transactionId', models.CharField()),
                ('companyName', models.CharField(blank=True, null=True)),
                ('bankStatement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pdfstatement.bankstatement')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdfstatement.transactioncategory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bankStatement', 'transactionId'), name='unique_bankStatement_transactionId')],
            },
        ),
    ]
