# Generated by Django 5.2.5 on 2025-08-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstatement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='pdfParserVersion',
        ),
    ]
