# Generated by Django 5.2.5 on 2025-08-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstatement', '0002_remove_bankstatement_pdfparserversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='pdfParserVersion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdfstatement.bankstatementparser'),
        ),
    ]
