# Generated by Django 5.2.5 on 2025-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstatement', '0003_bankstatement_pdfparserversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='categorizedByAI',
            field=models.BooleanField(default=False),
        ),
    ]
