# Generated by Django 5.2.5 on 2025-08-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstatement', '0004_bankstatement_categorizedbyai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='categorizedByAI',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
