# Generated by Django 5.2.5 on 2025-08-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstatement', '0005_alter_bankstatement_categorizedbyai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='categorizedByAI',
            field=models.BooleanField(default=False),
        ),
    ]
