# Generated by Django 5.2.5 on 2025-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfstatement', '0008_alter_bankstatement_categorizedbyai'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='periodEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='periodStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
